WIP: Intercept redirect on metrics application's endpoint and give a clear error message
orange-cloudfoundry/promfetcher pull request #38
Opened 2022-11-22 14:39 UTC by dchauviere

If an application respond with a redirect on the metrics endpoint, promfetcher could follow the redirection with external url instead of instance url (and could generate an error difficult to understand)!

For clarity, this PR intercept the redirect and return an error (via `promfetcher_scrape_error` metric)

2022-11-22 16:30 UTC, psycofdj requested changes
Thanks for the PR @dchauviere, here is some few little comments.

2022-11-22 16:30 UTC, psycofdj commented
I'm 100% in favor of this change, anything that makes error more understandable is good. However I have concerns on how bumping this into production where all metrics relying on a redirect will break.

2022-11-28 22:29 UTC, dchauviere commented on clients/backend.go
> +				return errors.New(fmt.Sprintf("Promfetcher don't follow redirect : %s redirect to %s.", req.URL, via[0].URL))
check done ! but yes it cannot happen : 'via' represent previous request !

2022-11-28 22:34 UTC, dchauviere commented on clients/backend.go
> +	if ( ! followRedirect ) {
it's proper ! -> done !

2022-11-28 22:36 UTC, dchauviere commented on clients/backend.go
> +			if (req.URL.Host == via[0].URL.Host) {
as discussed, we give here, a chance to follow a legitimate redirect (relative or same host as previous)

2022-11-29 13:50 UTC, psycofdj commented
thanks @dchauviere

2022-11-29 13:50 UTC, merged